/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class akibot_jni_java_AkibotJniLibrary */

#ifndef _Included_akibot_jni_java_AkibotJniLibrary
#define _Included_akibot_jni_java_AkibotJniLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    getDistance
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_akibot_jni_java_AkibotJniLibrary_getDistance
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
