/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class akibot_jni_java_DistanceSR05 */

#ifndef _Included_akibot_jni_java_DistanceSR05
#define _Included_akibot_jni_java_DistanceSR05
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     akibot_jni_java_DistanceSR05
 * Method:    distanceEchoMicros
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_akibot_jni_java_DistanceSR05_distanceEchoMicros
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
