/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class akibot_jni_java_AkibotJniLibrary */

#ifndef _Included_akibot_jni_java_AkibotJniLibrary
#define _Included_akibot_jni_java_AkibotJniLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_akibot_jni_java_AkibotJniLibrary_initialize
  (JNIEnv *, jobject);

/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    getDistance
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_akibot_jni_java_AkibotJniLibrary_getDistance
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    servo
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_akibot_jni_java_AkibotJniLibrary_servo
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    pulseIn
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_akibot_jni_java_AkibotJniLibrary_pulseIn
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     akibot_jni_java_AkibotJniLibrary
 * Method:    echoLocator
 * Signature: (IIIIIIIIIIIIIZ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_akibot_jni_java_AkibotJniLibrary_echoLocator
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
